version: '3'
services:
  bot:
    build: .
    image: ekanjibot
    container_name: ekanjibot
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./assets:/app/assets
    restart: on-failure:2