"""initial schema

Revision ID: c6521dae8f94
Revises:
Create Date: 2026-04-02 20:19:19.596060

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6521dae8f94"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fonts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "character_glyphs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character", sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
        sa.Column("custom_emoji_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("file_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("emoji_list", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("font_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["font_id"],
            ["fonts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    op.create_index(op.f("ix_character_glyphs_font_id"), "character_glyphs", ["font_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
        sa.Column("preferred_font_id", sa.Integer(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["preferred_font_id"],
            ["fonts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_table(
        "sticker_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pack_name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("pack_index", sa.Integer(), nullable=False),
        sa.Column("sticker_count", sa.Integer(), nullable=False),
        sa.Column("max_stickers", sa.Integer(), nullable=False),
        sa.Column("pack_type", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("is_full", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pack_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sticker_sets")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_character_glyphs_font_id"), table_name="character_glyphs")
    op.drop_table("character_glyphs")
    op.drop_table("fonts")
    # ### end Alembic commands ###
